Latest generator
PrefectHQ/prefect-databricks pull request #6
Opened 2022-08-05 02:26 UTC by ahuang11

## Summary

Use latest generator to generate tasks.

## Relevant Issue(s)

## Checklist
- [ ] Summarized PR's changes in [CHANGELOG.md](https://github.com/PrefectHQ/prefect-databricks/blob/main/CHANGELOG.md)

2022-08-05 16:51 UTC, desertaxle requested changes

2022-08-06 04:46 UTC, ahuang11 commented on docs/models.md
> +::: prefect_databricks.models
It seems to work for me.
![image](https://user-images.githubusercontent.com/15331990/183234310-c2434e4d-fc59-4c09-aa24-d3f27cd3a292.png)

2022-08-08 16:07 UTC, desertaxle commented on docs/models.md
> +::: prefect_databricks.models
Interesting. Should be good then. We'll just make sure to check that it works when deployed to GitHub pages.

2022-08-09 04:11 UTC, ahuang11 commented
Not too sure how to handle missing models in docstring. The root problem is that the models don't have docstrings, so mkdocs hides them.

For example, the first model:
```
class AutoScale(BaseModel):
    class Config:
        extra = Extra.allow
        allow_mutation = False

    max_workers: Optional[int] = Field(
        None,
        description=(
            "The maximum number of workers to which the cluster can scale up when"
            " overloaded. max_workers must be strictly greater than min_workers."
        ),
    )
    min_workers: Optional[int] = Field(
        None,
        description=(
            "The minimum number of workers to which the cluster can scale down when"
            " underutilized. It is also the initial number of workers the cluster has"
            " after creation."
        ),
    )
```

This doesn't show in the docs because it's missing a docstring:
![image](https://user-images.githubusercontent.com/15331990/183562342-1f699db9-7b59-4f28-ac89-958a60eda439.png)

However, if I manually input a dummy docstring:
```
class AutoScale(BaseModel):
    """a"""
```
![image](https://user-images.githubusercontent.com/15331990/183562432-85e59b75-a090-4c39-b29d-ef55a2e6d943.png)

It shows up, but it doesn't include args.

2022-08-12 05:44 UTC, ahuang11 commented
I couldn't find a way to monkeypatch datamodel code generator, so I did a simple string replacement instead. Seems to work well:

![image](https://user-images.githubusercontent.com/15331990/184291919-4b498f50-b454-44f1-a748-35b5ae9c68dd.png)

2022-08-12 20:01 UTC, desertaxle requested changes
I think this is good to go once we sort out a couple of items around the `DatabricksCredentials` block.

2022-08-13 06:19 UTC, ahuang11 commented on README.md
> +DATABRICKS_INSTANCE = "dbc-ab1c23d4-567e.cloud.databricks.com"
Okay, I've refactored the generator to automatically parse the necessary arguments in the server base_url

2022-08-15 20:53 UTC, desertaxle approved these changes

2022-08-15 21:04 UTC, desertaxle approved these changes

2022-08-15 21:06 UTC, merged